[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
  let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
  let cmd = 'make -f make_cygwin.mak'
elseif execute('gmake')
  let cmd = 'gmake'
else
  let cmd = 'make'
 endif
 let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'NeoTerm/NeoTerm'
if = "has('nvim')"
hook_add = '''
nnoremap <silent> ,rc :<C-u>TREPLSendFile<CR>
nnoremap <silent> ,rl :<C-u>TREPLSendLine<CR>
vnoremap <silent> ,rl :<C-u>TREPLSendSelection<CR>
nnoremap <silent> vt :<C-u>Ttoggle<CR>
nnoremap <silent> vs :terminal<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap <silent> fb :<C-u>Unite Buffer<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['ale', 'vim-gitbranch']
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap [nerdtree] <Nop>
nmap <C-h> [nerdtree]

nnoremap [nerdtree]<C-h> :<C-u>NERDTreeToggle<CR>
nnoremap [nerdtree]<C-f> :<C-u>NERDTreeFind<CR>
'''

[[plugins]]
repo = 'raphamorim/lucario'
hook_add = '''
colorscheme lucario
hi Visual ctermbg=90
hi SpellCap ctermbg=3132
'''

# TODO: 以下はlazyでも動きそうだけど動かなかったのでlazyについて調べて対応する
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'

# colroscheme。採用していないのが気分で切り替える
# [[plugins]]
# repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'migrs/qfixhowm'
hook_add = '''
source ~/.config/nvim/plugins/qfixhowm.vim
'''
